/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as PairRouteImport } from './routes/pair'
import { Route as RoutinesRouteImport } from './routes/routines'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as DemoIndexRouteImport } from './routes/demo.index'
import { Route as DemoApprovalsRouteImport } from './routes/demo.approvals'
import { Route as DemoSettingsRouteImport } from './routes/demo.settings'
import { Route as DemoAgentsAgentIdRouteImport } from './routes/demo.agents.$agentId'
import { Route as DemoAgentsAgentIdRunsRunIdRouteImport } from './routes/demo.agents.$agentId_.runs.$runId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const PairRoute = PairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutinesRoute = RoutinesRouteImport.update({
  id: '/routines',
  path: '/routines',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoRoute,
} as any)
const DemoApprovalsRoute = DemoApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => DemoRoute,
} as any)
const DemoSettingsRoute = DemoSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DemoRoute,
} as any)
const DemoAgentsAgentIdRoute = DemoAgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => DemoRoute,
} as any)
const DemoAgentsAgentIdRunsRunIdRoute =
  DemoAgentsAgentIdRunsRunIdRouteImport.update({
    id: '/agents/$agentId_/runs/$runId',
    path: '/agents/$agentId/runs/$runId',
    getParentRoute: () => DemoRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/demo': typeof DemoRouteWithChildren
  '/download': typeof DownloadRoute
  '/missions': typeof MissionsRoute
  '/pair': typeof PairRoute
  '/routines': typeof RoutinesRoute
  '/setup': typeof SetupRoute
  '/demo/approvals': typeof DemoApprovalsRoute
  '/demo/settings': typeof DemoSettingsRoute
  '/demo/': typeof DemoIndexRoute
  '/demo/agents/$agentId': typeof DemoAgentsAgentIdRoute
  '/demo/agents/$agentId/runs/$runId': typeof DemoAgentsAgentIdRunsRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/download': typeof DownloadRoute
  '/missions': typeof MissionsRoute
  '/pair': typeof PairRoute
  '/routines': typeof RoutinesRoute
  '/setup': typeof SetupRoute
  '/demo/approvals': typeof DemoApprovalsRoute
  '/demo/settings': typeof DemoSettingsRoute
  '/demo': typeof DemoIndexRoute
  '/demo/agents/$agentId': typeof DemoAgentsAgentIdRoute
  '/demo/agents/$agentId/runs/$runId': typeof DemoAgentsAgentIdRunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/demo': typeof DemoRouteWithChildren
  '/download': typeof DownloadRoute
  '/missions': typeof MissionsRoute
  '/pair': typeof PairRoute
  '/routines': typeof RoutinesRoute
  '/setup': typeof SetupRoute
  '/demo/approvals': typeof DemoApprovalsRoute
  '/demo/settings': typeof DemoSettingsRoute
  '/demo/': typeof DemoIndexRoute
  '/demo/agents/$agentId': typeof DemoAgentsAgentIdRoute
  '/demo/agents/$agentId_/runs/$runId': typeof DemoAgentsAgentIdRunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/demo'
    | '/download'
    | '/missions'
    | '/pair'
    | '/routines'
    | '/setup'
    | '/demo/approvals'
    | '/demo/settings'
    | '/demo/'
    | '/demo/agents/$agentId'
    | '/demo/agents/$agentId/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/download'
    | '/missions'
    | '/pair'
    | '/routines'
    | '/setup'
    | '/demo/approvals'
    | '/demo/settings'
    | '/demo'
    | '/demo/agents/$agentId'
    | '/demo/agents/$agentId/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/approvals'
    | '/demo'
    | '/download'
    | '/missions'
    | '/pair'
    | '/routines'
    | '/setup'
    | '/demo/approvals'
    | '/demo/settings'
    | '/demo/'
    | '/demo/agents/$agentId'
    | '/demo/agents/$agentId_/runs/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRoute
  DemoRoute: typeof DemoRouteWithChildren
  DownloadRoute: typeof DownloadRoute
  MissionsRoute: typeof MissionsRoute
  PairRoute: typeof PairRoute
  RoutinesRoute: typeof RoutinesRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pair': {
      id: '/pair'
      path: '/pair'
      fullPath: '/pair'
      preLoaderRoute: typeof PairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routines': {
      id: '/routines'
      path: '/routines'
      fullPath: '/routines'
      preLoaderRoute: typeof RoutinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/approvals': {
      id: '/demo/approvals'
      path: '/approvals'
      fullPath: '/demo/approvals'
      preLoaderRoute: typeof DemoApprovalsRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/settings': {
      id: '/demo/settings'
      path: '/settings'
      fullPath: '/demo/settings'
      preLoaderRoute: typeof DemoSettingsRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/agents/$agentId': {
      id: '/demo/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/demo/agents/$agentId'
      preLoaderRoute: typeof DemoAgentsAgentIdRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/agents/$agentId_/runs/$runId': {
      id: '/demo/agents/$agentId_/runs/$runId'
      path: '/agents/$agentId/runs/$runId'
      fullPath: '/demo/agents/$agentId/runs/$runId'
      preLoaderRoute: typeof DemoAgentsAgentIdRunsRunIdRouteImport
      parentRoute: typeof DemoRoute
    }
  }
}

interface DemoRouteChildren {
  DemoApprovalsRoute: typeof DemoApprovalsRoute
  DemoSettingsRoute: typeof DemoSettingsRoute
  DemoIndexRoute: typeof DemoIndexRoute
  DemoAgentsAgentIdRoute: typeof DemoAgentsAgentIdRoute
  DemoAgentsAgentIdRunsRunIdRoute: typeof DemoAgentsAgentIdRunsRunIdRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoApprovalsRoute: DemoApprovalsRoute,
  DemoSettingsRoute: DemoSettingsRoute,
  DemoIndexRoute: DemoIndexRoute,
  DemoAgentsAgentIdRoute: DemoAgentsAgentIdRoute,
  DemoAgentsAgentIdRunsRunIdRoute: DemoAgentsAgentIdRunsRunIdRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRoute,
  DemoRoute: DemoRouteWithChildren,
  DownloadRoute: DownloadRoute,
  MissionsRoute: MissionsRoute,
  PairRoute: PairRoute,
  RoutinesRoute: RoutinesRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
