"""The generated Blender script for one render3d run (static text + payload builder).

Everything the script needs lives in ONE JSON payload (scene + render settings + steps
with their absolute output paths), so the script text is constant and unit-testable
without Blender. The runner writes both files into the run's ``work/`` dir — they are
kept as evidence of exactly what ran.

Per-step status is machine-readable: ``EEZE-STEP <id> OK|FAIL <seconds>s <detail>``;
a step that raises does not kill the ones after it.
"""

from __future__ import annotations

from pathlib import Path

from .spec import Scene3DSpec

EXTENSIONS = {
    "save_blend": ".blend",
    "render_still": ".png",
    "render_animation": ".mp4",
    "export_glb": ".glb",
}


def build_payload(spec: Scene3DSpec, steps_out: dict[str, Path], *, out_dir: Path) -> dict:
    """The JSON handed to Blender: the spec's scene/render + per-step absolute outputs."""
    steps = []
    for step in spec.steps:
        steps.append(
            {
                "id": step.id,
                "op": step.op,
                "frame": step.frame or 1,
                "out": steps_out[step.id].resolve().as_posix(),
            }
        )
    return {
        "name": spec.name,
        "scene": spec.scene.model_dump(),
        "render": spec.render.model_dump(),
        "steps": steps,
        "out_dir": out_dir.resolve().as_posix(),
    }


SCRIPT = r'''"""Generated by eeze render3d — do not hand-edit: the spec JSON is the source of truth.

Runs inside Blender:  blender -b --factory-startup -noaudio --python run_blender.py -- <scene.json>
Builds the scene once, then executes every step in order, printing machine-readable
status lines (EEZE-STEP <id> OK|FAIL <seconds>s <detail>) and continuing after a failure.
"""

import json
import math
import os
import sys
import time
import traceback

argv = sys.argv[sys.argv.index("--") + 1 :]
with open(argv[0], encoding="utf-8") as fh:
    SPEC = json.load(fh)

import bpy  # noqa: E402
from mathutils import Vector  # noqa: E402


def build_scene(spec):
    render = spec["render"]
    bpy.ops.wm.read_factory_settings(use_empty=True)
    scn = bpy.context.scene
    scn.frame_start = 1
    scn.frame_end = int(render["frames"])

    world = bpy.data.worlds.new("eeze-world")
    scn.world = world
    if not world.use_nodes:  # assigning it when already True warns (gone in Blender 6)
        world.use_nodes = True
    background = world.node_tree.nodes["Background"]
    background.inputs[0].default_value = (*render["background"], 1.0)
    background.inputs[1].default_value = 1.0

    for obj in spec["scene"]["objects"]:
        kind = obj["kind"]
        params = obj.get("params") or {}
        if kind == "cube":
            bpy.ops.mesh.primitive_cube_add(size=params.get("size", 2.0))
        elif kind == "sphere":
            bpy.ops.mesh.primitive_uv_sphere_add(
                radius=params.get("radius", 1.0), segments=int(params.get("segments", 48))
            )
        elif kind == "torus":
            bpy.ops.mesh.primitive_torus_add(
                major_radius=params.get("radius", 1.0),
                minor_radius=params.get("minor_radius", 0.3),
                major_segments=int(params.get("segments", 64)),
                minor_segments=int(params.get("minor_segments", 24)),
            )
        elif kind == "cylinder":
            bpy.ops.mesh.primitive_cylinder_add(
                radius=params.get("radius", 1.0),
                depth=params.get("depth", 2.0),
                vertices=int(params.get("vertices", 48)),
            )
        elif kind == "cone":
            bpy.ops.mesh.primitive_cone_add(
                radius1=params.get("radius", 1.0),
                depth=params.get("depth", 2.0),
                vertices=int(params.get("vertices", 48)),
            )
        elif kind == "plane":
            bpy.ops.mesh.primitive_plane_add(size=params.get("size", 10.0))
        elif kind == "text":
            bpy.ops.object.text_add()
            text_obj = bpy.context.object
            text_obj.data.body = obj.get("text") or ""
            text_obj.data.size = params.get("size", 1.0)
            text_obj.data.extrude = params.get("extrude", 0.06)
            text_obj.data.align_x = "CENTER"
            text_obj.data.align_y = "CENTER"
        else:
            raise ValueError(f"unknown object kind: {kind}")

        ob = bpy.context.object
        if obj.get("name"):
            ob.name = obj["name"]
        ob.location = obj["location"]
        ob.rotation_euler = tuple(math.radians(a) for a in obj["rotation"])
        ob.scale = obj["scale"]
        mat = bpy.data.materials.new(f"{ob.name}-mat")
        if not mat.use_nodes:  # same deprecation as the world above
            mat.use_nodes = True
        bsdf = mat.node_tree.nodes["Principled BSDF"]
        bsdf.inputs["Base Color"].default_value = (*obj["color"], 1.0)
        bsdf.inputs["Metallic"].default_value = obj["metallic"]
        bsdf.inputs["Roughness"].default_value = obj["roughness"]
        ob.data.materials.append(mat)

    for light in spec["scene"]["lights"]:
        kind = light["kind"].upper()
        bpy.ops.object.light_add(type=kind, location=light["location"])
        lo = bpy.context.object
        lo.data.energy = light["energy"]
        lo.data.color = light["color"]
        if kind == "AREA":
            lo.data.size = light["size"]
        lo.rotation_euler = (
            (Vector((0, 0, 0)) - Vector(light["location"])).to_track_quat("-Z", "Y").to_euler()
        )

    cam_spec = spec["scene"]["camera"]
    bpy.ops.object.camera_add(location=cam_spec["location"])
    cam = bpy.context.object
    cam.data.lens = cam_spec["lens"]
    look_at = Vector(cam_spec["look_at"])
    cam.rotation_euler = (look_at - Vector(cam_spec["location"])).to_track_quat("-Z", "Y").to_euler()
    scn.camera = cam

    orbit = cam_spec.get("orbit")
    if orbit:
        offset = Vector(cam_spec["location"]) - look_at
        radius = orbit.get("radius") if orbit.get("radius") is not None else offset.length
        height = orbit.get("height") if orbit.get("height") is not None else offset.z
        # The spec's camera azimuth sets where the orbit STARTS (a hard-coded +X start
        # ignored it and shot the back of a facing object — found in the first demo run).
        start_angle = math.atan2(offset.y, offset.x) if (offset.x or offset.y) else 0.0
        center = bpy.data.objects.new("orbit-center", None)
        scn.collection.objects.link(center)
        center.location = look_at
        cam.parent = center
        cam.location = (radius, 0.0, height)
        cam.rotation_euler = (0.0, 0.0, 0.0)
        track = cam.constraints.new("TRACK_TO")
        track.target = center
        center.rotation_euler = (0.0, 0.0, start_angle)
        # Interpolation set via preferences: Blender 4.4+ slotted actions moved fcurves
        # off the Action object, so the old `action.fcurves` loop raises AttributeError
        # on 5.2 (measured) — this route works across versions.
        bpy.context.preferences.edit.keyframe_new_interpolation_type = "LINEAR"
        center.keyframe_insert("rotation_euler", frame=scn.frame_start)
        center.rotation_euler = (
            0.0,
            0.0,
            start_angle + math.radians(360.0 * float(orbit.get("revolutions", 1.0))),
        )
        center.keyframe_insert("rotation_euler", frame=scn.frame_end)

    scn.render.engine = render["engine"]
    scn.render.resolution_x = int(render["resolution"][0])
    scn.render.resolution_y = int(render["resolution"][1])
    scn.render.resolution_percentage = 100
    scn.render.film_transparent = bool(render["film_transparent"])
    scn.render.fps = int(render["fps"])
    if render.get("samples") is not None:
        if render["engine"] == "CYCLES":
            scn.cycles.samples = int(render["samples"])
            scn.cycles.device = "CPU"
        else:
            try:
                scn.eevee.taa_render_samples = int(render["samples"])
            except AttributeError:
                pass
    return scn


def step_save_blend(scn, step, target):
    bpy.ops.wm.save_as_mainfile(filepath=target)
    return f"{os.path.getsize(target)} bytes"


def step_render_still(scn, step, target):
    image = scn.render.image_settings
    if hasattr(image, "media_type"):  # Blender 5.x: a still after an animation must reset it
        image.media_type = "IMAGE"
    image.file_format = "PNG"
    scn.render.use_file_extension = False
    scn.render.filepath = target
    scn.frame_set(int(step.get("frame") or 1))
    bpy.ops.render.render(write_still=True)
    return f"{os.path.getsize(target)} bytes"


def step_render_animation(scn, step, target):
    image = scn.render.image_settings
    # Blender 5.x: FFMPEG only appears in the format enum after media_type = "VIDEO"
    # (measured: setting file_format first raises `enum "FFMPEG" not found`).
    if hasattr(image, "media_type"):
        image.media_type = "VIDEO"
    image.file_format = "FFMPEG"
    scn.render.ffmpeg.format = "MPEG4"
    scn.render.ffmpeg.codec = "H264"
    scn.render.ffmpeg.constant_rate_factor = "MEDIUM"
    scn.render.use_file_extension = False  # exact path: no double extension
    scn.render.filepath = target
    bpy.ops.render.render(animation=True)
    return f"{os.path.getsize(target)} bytes"


def step_export_glb(scn, step, target):
    bpy.ops.export_scene.gltf(filepath=target, export_format="GLB")
    return f"{os.path.getsize(target)} bytes"


OPS = {
    "save_blend": step_save_blend,
    "render_still": step_render_still,
    "render_animation": step_render_animation,
    "export_glb": step_export_glb,
}


def main():
    t0 = time.time()
    try:
        scn = build_scene(SPEC)
    except Exception as exc:
        print(f"EEZE-BUILD-FAIL {type(exc).__name__}: {exc}", flush=True)
        traceback.print_exc()
        sys.exit(3)
    print(f"EEZE-SCENE {time.time() - t0:.2f}s", flush=True)

    for step in SPEC["steps"]:
        t1 = time.time()
        target = step["out"]
        try:
            os.makedirs(os.path.dirname(target), exist_ok=True)
            detail = OPS[step["op"]](scn, step, target)
            print(f"EEZE-STEP {step['id']} OK {time.time() - t1:.2f}s {detail}", flush=True)
        except Exception as exc:  # keep going: a failed step must not hide the next ones
            print(
                f"EEZE-STEP {step['id']} FAIL {time.time() - t1:.2f}s "
                f"{type(exc).__name__}: {exc}",
                flush=True,
            )
            traceback.print_exc()
    print("EEZE-DONE", flush=True)


main()
'''
